### ISSUE TITLE
How to connect

### ISSUE THREAD

**Issue by raghavendrajain** [AdityaSolanki189/adityasolanki189#1]
Hi Aditya, 
Loved your work on `transcriber` for Google Meet. Would like to connect, I may have something for you. 
Can you share your email? Thanks!

**Comment by AdityaSolanki189** [comment]
Hey!
Sure let's connect
***@***.***

**Comment by raghavendrajain** [comment]
Thanks, the email id does not get displayed though. Can you update it in your Github profile and I will grab it from there @AdityaSolanki189

**Comment by AdityaSolanki189** [comment]
Right, will do that
